"""Step 4: 500x500 RGBA PNG -> 32x32 RGB PNG, and normalization to [-1, 1]."""

import numpy as np
import torch
from PIL import Image


class ImagePreprocessor:
    """Prepares the Cartoon Set images for the diffusion model."""

    def __init__(self, config):
        """Args:
            config: the project Config (uses IMAGE_SIZE, BACKGROUND, IMAGES_DIR,
                RESIZED_IMAGES_DIR, PREVIEW_FILE).
        """
        self.config = config
        self.size = config.IMAGE_SIZE
        self.background = tuple(config.BACKGROUND)

    def prepare_image(self, path):
        """Open one PNG, put it on the background and resize it.

        The background is added before resizing: the contour pixels are semi-transparent,
        and without it their full color would stay, making the contours darker.

        Args:
            path: PNG file of the raw dataset (RGBA, 500x500).

        Returns:
            PIL image, RGB, IMAGE_SIZE x IMAGE_SIZE, values 0-255.
        """
        image = Image.open(path).convert('RGBA')
        canvas = Image.new('RGBA', image.size, self.background + (255,))
        canvas.alpha_composite(image)
        return canvas.convert('RGB').resize((self.size, self.size), Image.LANCZOS)

    @staticmethod
    def normalize(image):
        """Bring the pixels from 0-255 to [-1, 1], the scale of the Gaussian noise.

        Static method: it needs no settings, call it as ImagePreprocessor.normalize(image).

        Args:
            image: PIL image, RGB.

        Returns:
            float tensor of shape (3, H, W) with values in [-1, 1].
        """
        pixels = torch.from_numpy(np.array(image))       # (H, W, 3), values 0-255
        return pixels.permute(2, 0, 1).float() / 127.5 - 1

    @staticmethod
    def denormalize(tensor):
        """Inverse of normalize, to save an image generated by the model.

        Args:
            tensor: float tensor of shape (3, H, W); values outside [-1, 1] are cut first.

        Returns:
            PIL image, RGB, values 0-255.
        """
        pixels = ((tensor.clamp(-1, 1) + 1) * 127.5).round().to(torch.uint8)
        return Image.fromarray(pixels.permute(1, 2, 0).cpu().numpy())

    def process_dataset(self, data):
        """Prepare the images listed in the captions table, save them and save a preview.

        Args:
            data: the captions table of all the images (column 'file').
        """
        self.config.RESIZED_IMAGES_DIR.mkdir(parents=True, exist_ok=True)
        first_images = []
        for i, name in enumerate(data['file']):
            image = self.prepare_image(self.config.IMAGES_DIR / name)
            image.save(self.config.RESIZED_IMAGES_DIR / name)
            if len(first_images) < 64:
                first_images.append(image)
            if (i + 1) % 2000 == 0:
                print(f'   {i + 1}/{len(data)} images')
        self.save_preview(first_images, self.config.PREVIEW_FILE)

    def save_preview(self, images, path):
        """Save images in a grid of 8 columns, enlarged 4 times to see the real pixels.

        Args:
            images: list of PIL images (64 for the data preview: 8 rows; 16 for a training grid: 2 rows).
            path: destination PNG file.
        """
        side = self.size * 4
        rows = (len(images) + 7) // 8
        grid = Image.new('RGB', (8 * side, rows * side), self.background)
        for i, image in enumerate(images):
            grid.paste(image.resize((side, side), Image.NEAREST), ((i % 8) * side, (i // 8) * side))
        grid.save(path)
